
int slidenumber = 0;

int counter;
//all of my data for my slides are stored in arrays, based on the current slide_number from main
String[] storytext = {
 "                          \n \n \n \nThis is an interactive version of a novella by Carmen Maria Machado. Its a unique piece that uses the names of all 272 episodes (and 12 seasons) of Law and Order SVU as inspiration, while also providing social commentary on the staggering amount of violence we regularly watch on TV (so be warned, it is pretty violent). The story is set up as short capsule summaries for each of these episodes.",
 " ",
 "Stabler and Benson investigate the murder and castration of a New York City cab driver. They discover that the victim assumed the identity of another man years before because he was wanted by police. In the end, Stabler discovers that the stolen identity of the man in question was also stolen, and he and Benson have to begin the investigation all over again. That night, as he unsuccessfully tries to sleep, Stabler begins to hear a strange noise. A deep drumming, two beats. It seems like it’s coming from his basement. When he investigates the basement, it sounds like it’s coming from outside.",
 "Emily couldn’t bear getting dressed alone anymore. The solitary donning of shoes broke her heart. The unlocked front door, through which any neighbor could wander, would have been an afterthought, but there was no thought, after.",
 "Two underage models are attacked while walking home from a club. They are raped and murdered. To add insult to injury, they are confused with two other raped and murdered underage models, who coincidentally are their respective twins, and both pairs are buried beneath the wrong tombstones.",
 "Benson and Stabler investigate the murder of a young woman who is initially believed to be a prostitute and the latest in a long line of victims. “I hate this goddamned city,” Benson says to Stabler, dabbing her eyes with a deli napkin. Stabler rolls his eyes and starts the car.",
 "The old DA irons her hair before court, the way her mother showed her. After she loses the case, she packs three changes of clothes in a suitcase and gets into her car. She calls Benson from her cell phone. “Sorry, buddy. Hitting the road. Not sure when I’ll be back.” Benson pleads with her to stay. The old DA tosses the cell phone onto the road and pulls away from the curb. A passing taxi reduces it to splinters.",
 "The second time the basketball team covered up a murder, the coach decided that he’d finally had enough.",
 "They found the boy in Central Park, looking like no one had ever loved him. “His body was crawling with ants,” Stabler said. “Ants.” Two days later, they arrest his teacher, who as it turns out had loved him just fine.",
 "Benson and Stabler aren’t allowed to notch any of the precinct’s furniture, so they each have their own private system. Benson’s headboard has eight scores that run along the curved oak edge like a spine. Stabler’s kitchen chair has nine.",
 "Benson takes the bag of rotten vegetables out of the trunk when Stabler isn’t looking. She throws it in a garbage can and it hits the empty bottom, wet and heavy. It splits open like a body that’s been in the Hudson.",
 "“It was inside of me,” the woman says, pulling the bendy straw out of shape like a misused accordion. “But now it is outside of me. I would like to keep it that way.",
 "Stabler and Benson will never forget the case where the outcome was so much worse than the crime.",
 "When they bring the mother up to the stand, the new DA asks her what her name is. She closes her eyes, shakes her head, rocks back and forth in her chair. She begins to sing a song softly under her breath, not in English, the syllables rolling out of her mouth like smoke. The DA looks to the judge for help, but he is staring at the witness, his eyes distant as if he is lost inside of his own head.",
 "A disoriented, naked, pregnant woman is discovered wandering around Midtown. She is arrested for indecent exposure.",
 "Stabler discovers that even New York ends.",
 "“You can’t do this to me!” the man shouts as he is escorted to the witness stand. “Don’t you know who I am?” The DA closes her eyes. “Sir, I just need you to confirm that you did tell police that you saw a blue Honda fleeing the scene.” The man pounds his open hand on the witness stand in defiance. “I do not recognize your authority!” The mother of the dead girl begins screaming so loudly that her husband carries her out of the courtroom.",
 "Stabler never told Benson about his little brother. But he also never told her about his older brother, which was more acceptable, because he didn’t know about him, either.",
 "Father Jones has never touched a child, but when he closes his eyes at night, he still remembers his high school girlfriend: her soft thighs, her lined hands, the way she dropped off that roof like a falcon.",
 "Convinced that her teenaged daughter is in danger from cyber predators, a father takes a crowbar to the family computer. He throws the remaining pieces into the fireplace, strikes a match. His daughter complains of a light head, a burning in her chest. She calls him “Mom” with tears in her voice. She dies on a Saturday.",
 "Stabler discovers that his wife believes she saw a UFO, back when she was in her early twenties. He lies awake all night, wondering if this explains the memory loss, the PTSD, the night terrors. His wife wakes up weeping and screaming, on cue.",
 "At night, Stabler makes a list of the day’s regrets. “Didn’t tell Benson,” he scrawls. “Ate more burrito than I had room for. Misspent that gift card. Hit that guy harder than I meant to.” His wife comes up behind him and rubs his shoulder idly before crawling into bed. “Haven’t told my wife today. Will probably not tell her tomorrow.”",
 "The ghost of one of the murdered, misburied underage models begins to haunt Benson. She has bells for eyes, tiny brass ones dangling from the top of each socket, the hammer not quite touching the cheekbone. The ghost does not know her own name. She stands over Benson’s bed, the right bell tinkling faintly, and then the left, and then the right again. This happens for four nights in a row, at 2:07 a.m. Benson starts sleeping with a crucifix and pungent ropes of garlic because she does not understand the difference between vampires and murdered teenagers. Not yet.",
 "The precinct’s interns are monsters. When it’s slow, they dick around on the phones. Into the dial tones, they chirp “SVU, Manhattan’s rapiest police department!” They have theories about Stabler and Benson. They place bets. They plant lilacs (Benson’s favorite) and daisies (Stabler’s) in the other’s lockers. The interns drug Benson’s and Stabler’s coffees and then, after they fall asleep in the back room, the interns shove the cots close together and place both the detectives in compromising positions. Benson and Stabler wake up, their hands on each other’s cheeks, both wet with tears.",
 "  ",
 "Benson wakes up in the middle of the night. She is not in her bed. She is in her pajamas, in the dark. Her hand is on a handle. A door is open. A confused-looking panda is watching her with dewy eyes. Benson shuts the door. She passes two llamas chewing thoughtfully on the sign for a hot dog stand. In the parking lot of the zoo, her car is idling against a cement post. She changes into the spare set of clothes she keeps in the trunk. She calls it in. “Eco-terrorists,” she tells Stabler. He nods, jots down something in his notebook. “Do you smell garlic?” he asks.",
 "Stabler dreams that a man at a Renaissance Faire insults Stabler’s wife, and Stabler punches him in his self-satisfied face. When Stabler wakes up, he decides to tell his wife this story. He rolls over. She is gone. Stabler has never been to a Renaissance Faire.",
 "“It’s not that I hate men,” the woman says. “I’m just terrified of them. And I’m okay with that fear.”",
 "Over breakfast, Stabler’s daughter asks him about Benson’s family. Stabler says that Benson doesn’t have a family. “You always say that family is a man’s one true wealth,” says Stabler’s daughter. Stabler thinks about this. “It’s true,” he says. “But Benson is not a man.”",
 "Benson keeps the condoms in her nightstand drawer refreshed, and throws the expired ones away. She dutifully takes her pill at the same time every morning. She makes dates and always keeps them.",
 "The girl-with-bells-for-eyes tells Benson to go to Brooklyn. They can communicate, now, with the bells. Benson taught herself Morse code. Benson never goes to Brooklyn, but she agrees. She rides the train late at night, so late that there is only one man in her car, and he is sleeping on a duffel bag. As they shoot through the tunnels, the man looks blearily at Benson, then unzips his duffel bag and vomits into it, almost politely. The vomit is white, like cream of wheat. He re-zips the bag. Benson gets off two stops too early, and ends up walking through Crown Heights for a very long time.",
 "Stabler works out every morning at the precinct. He does tricep curls. He does crunches. He jogs on a treadmill. He thinks he hears his daughter’s voice crying his name. Startled, he trips on the treadmill and his whole body slams against the cinderblock wall. The path rolls toward him in endless loops.",
 "“It was dark,” says Stabler’s wife. “I was walking home alone. It was raining. Well, not really raining. Spitting, I guess. Misting. It was misting and the light from the streetlamps was all pooled and golden, and thick, even, like it was a solid. And I was breathing deeply and it felt healthy, healthy and right to be walking through that night.” Stabler hears the drumming again. It shakes the water glass on the nightstand. Stabler’s wife doesn’t seem to notice.",
 "“Get out!” Benson screams, hurling pillows at the girl-with-bells-for-eyes. She’s brought a friend this time, a small girl with hair in tight cornrows and no mouth. She gets out of bed and tries to push them away, but her hands and upper body go through both of them as if they are nothing. They taste like mildew in her mouth. She remembers being eight and kneeling before the humidifier in her room, taking in the steam like it was the only way she could drink.",
 "“Stabler?” says Benson carefully. Stabler looks up from his raw knees. Benson unfolds the tiny square alcohol wipe and hands it to him. “Can I sit here? Can I help?” He nods wordlessly, lets her rub his knees. He hisses pain through his teeth. “What did you do?” she asks. “The treadmill? Are these from the treadmill?” Stabler shakes his head. He can’t say. He can’t.",
 "More regrets. The lines crowd the page. “Showed Benson my skinned knees. Allowed her to assist me. Not sure who I was thinking about when I had sex with my wife tonight.”",
 "The girl-with-bells-for-eyes tells Benson to go to Yonkers. Benson refuses and begins to burn sage in her apartment.",
 "Her apartment is so crowded with ghosts that, for the first time since she can remember, Benson stays at someone else’s place for the night. Her date is an investment banker, a boring and stupid man with a fat, piss-mean tabby who tries to suffocate Benson with her bulk. Benson hates him, but what else can she do?",
 "“I am not suppressing anything!” Stabler’s wife yells at him. “Tell me about the night with the aliens,” says Stabler. He is trying to learn. He is trying to figure it out. “It was misty,” she says. “It was spitting.” He hears the banging again, the tone, sounding from somewhere in the house. “Yes, I know, I know,” Stabler says. “The light pooled around the lamp posts.” “There were so many iron gates. I walked past them and ran my fingers over their loops and whorls, and then my fingers smelled like metal.” “Yes,” said Stabler. “But then what?” But his wife is asleep.",
 "The serial killer promises that there is a bomb hidden under a bench in Central Park. “Do you know how many benches there are in Central Park?” shouts Stabler, clutching an intern by his shirt collar. They send policemen to Central Park to chase people off benches like they are pigeons, or the homeless. Nothing happens.",
 "The girl-with-bells-for-eyes sends Benson into every borough. Benson rides the train. Eventually, she has seen every stop at least once. She is beginning to memorize the murals, the water stains, the smells. 59th Street smells like a urinal. Cortelyou smells, unnervingly, like lilacs. For the first time in a while, Benson thinks about Stabler. Back in her apartment, the girl-with-bells-for-eyes tries to tell Benson a story. I was a virgin. When he took me, I popped.",
 "“There is a case,” says the captain. “A young boy has accused his mother of hitting him with a toilet plunger. This is a tricky one, though. The boy is the son of a political heavyweight with deep pockets. He golfs with the mayor. His wife is—Benson? Benson, are you listening?”",
 "Stabler has determined that he is not even a little bit gay. He swallows his disappointment. His mouth tastes like orange peel.",
 "“Oh fuck,” says Stabler’s wife. “Fuck. Sweetie, the kids have lice. I need your help.” They stand the kids in the tub. The oldest daughter rolls her eyes. Her mother helps her scrub her scalp, and the youngest whines that the shampoo burns. Stabler feels serene for the first time in months.",
 "“The victim has ties to the modeling industry,” says the captain. “But we’re having trouble tracking down where she lived. She might have come from another country. She was only fourteen.” He hangs her autopsy photo on the bulletin board, her face flat and pale. The thumbtack pops into the cork and Benson jumps in her chair.",
 "Stabler hears it again. The sound, the drumming. It seems to come from the break room. When he goes there, it sounds like it is coming from the interrogation room. Inside the interrogation room, he hears it again. He bangs his hands on the two-way mirror, imitating the sound, hoping to lure it, hoping to see it, but all is quiet.",
 "  ",
 "In the middle of a sermon, Father Jones begins screaming. His parishioners look on in fear as he clings to the pulpit, wailing a name over and over. Convinced that this is an admission of guilt of some kind or another, the diocese calls Benson and Stabler. In his office, Benson knocks a pen off his desk, and Father Jones dives after it, howling.",
 "Benson reaches up from her bed, like a baby. The girl-with-bells-for-eyes stands over her, like a mother. Benson grabs at the bells, pulls them as hard as she can, and the ghost-girl jerks violently, and every lightbulb in Benson’s apartment explodes, covering the carpet with glass.",
 "First it’s a candy bar. The next day, a lighter. Stabler wants to stop, but he has long since learned to choose his battles.",
 "“Just tell me what you remember, Father.” Click. “She hated water and grass, so we picnicked on the top of her apartment building. She lived in that building with her mother. I loved her. I lost myself in her body. We lay a blanket over the gravel. I fed her orange slices. She told me that she was a prophet, and that she had a vision that one day, I would take an innocent life. I said no, no. She climbed up onto the cement wall that bordered the roof. She stood there and declared her vision again. She said she was sorry. She didn’t even fall like I expected. She simply knelt into the air.”",
 "Stabler finds Benson sleeping in the back room at the precinct on a sagging cot. She wakes up when the door opens. She looks like she has “run the gauntlet,” which is something Stabler’s mother used to say before she died. Come to think of it, it’s the last phrase Stabler can remember her speaking.",
 "Benson accidentally catches a rapist when she Google-stalks her newest OKCupid date. She can’t decide whether or not to mark this in the “success” (“caught rapist”) or “failure” (“date didn’t work out”) column. She marks both.",
 "Benson leaves her handsome date at the table, in the restaurant, waiting for the drinks. She walks down an empty side street. She takes off her shoes and walks down the center of the road. It is too hot for April. She can feel her feet darkening from the blacktop. She should be afraid of broken glass but she is not. In front of a vacant lot, she stops. She reaches down and touches the pavement. It is breathing. Its two-toned heartbeat makes her clavicle vibrate. She can feel it. She is suddenly, irrevocably certain that the earth is breathing. She knows that New York is riding the back of a giant monster. She knows this more clearly than she has ever known anything before.",
 "The phrase “run the gauntlet” is stuck in Stabler’s head, like water dipping and sluicing around his inner ear. He presses the muscles at the hinge of his jaw and cracks it. The crack takes the place of the single syllable of “run.” He does it again. Crack the gauntlet. Run the cracklet. Run.",
 "Stabler is worried about Benson, but he cannot tell her.",
 "Benson does her twice-monthly grocery trip. She drives her car to a grocery store in Queens and buys three hundred dollars worth of produce. It will make her fridge look like the garden of Eden. She will not eat it while she gnaws on chewy French toast in the Styrofoam container from the diner. The produce will, predictably, rot. Her fridge will smell overwhelmingly like dirt. She will collect it in garbage bags and throw it in the public trashcan near the station before her next trip.",
 "Stabler wakes up one night to find his wife staring at the ceiling, tears soaking the pillow next to her head. “It was spitting,” she says. “My fingers smelled like metal. I was so scared.” For the first time, Stabler understands.",
 "Benson crosses the street without looking. The taxi driver slams on his brakes, his bumper stopping a hairswidth from Benson’s shins. When she looks through the windshield, she sees a teenage boy in the passenger seat, eyes closed. When he opens then, the sun glints off the curves of the bells. The taxi driver screams at Benson as she stares.",
 "“Look at me, Dad!” Stabler’s daughter says, laughing, twirling. As clearly as if he is watching a movie, he sees her in two years’ time, swatting a boyfriend’s hands away in a backseat, harder and harder. She screams. Stabler starts. She has fallen to the ground and is clutching her ankle, crying.",
 "“You don’t understand,” says Father Jones to Benson. There are dark curves under his eyes, sacs the color of bruised apples. He is wearing a terrycloth bathrobe that says “Susan” in machine-stitched cursive letters on the breast pocket. “I can’t help you. I’m having a crisis of faith.” Benson puts her hand on the door. “I’m having a crisis of function,” she says. “Tell me. What do you know about ghosts?”",
 "The medical examiner pulls back the sheet from the dead girl’s face. “Raped and strangled,” she says, her voice hollow. “Your murderer pressed their thumbs into the girl’s windpipe until she died. No prints, though.” Stabler thinks that the girl looks a little like his wife’s high school photo. Benson is certain she can see the jelly of the girl’s eyes receding beneath their closed lids, certain she can hear the sound of bells. In the car, they are both quiet.",
 "They question everyone they can think of: her friends and enemies. The girls she bullied, the boys who loved her and hated her, the parents who thought she was wonderful and the parents who thought she was bad news. Benson stumbles into the precinct late, bleary-eyed. “My theory,” she says, drinking her coffee slowly, with shaking hands, “my theory is that it was her coach, and my theory is that the missing underwear will be found in his office.” The search warrant is issued so quickly that they find the underwear in his top desk drawer, still damp with blood.",
 "Benson doesn’t know how to explain to Stabler the heartbeat beneath the ground. She is certain that she can hear it all the time now, deep and low. The girls-with-bells-for-eyes have taken to knocking before coming in. Sometimes. Benson takes taxis to far-away neighborhoods, gets down on her hands and knees on the street and the sidewalk and once, in a woman’s vegetable garden that took up her entire postage-stamp lawn. She can hear it everywhere. The drumming, echoing, echoing in the deep.",
 "Benson can translate the bells well, now. She pulls her pillow over her head until she can barely breathe. Give us voices. Give us voices. Give us voices. Tell him. Tell him. Tell him. Find us. Find us. Find us. Please. Please. Please.",
 "Benson gets a pack of small children. Their bells are especially tiny, the ring higher than most. Benson is drunk. She holds her bed, which feels like an amusement park ride, pitching and rolling. We will never ride the Tilt-a-Whirl again, ever. Get up! Get up! they command her. She puts her head on her cell phone and uses speed-dial. “My theory,” she says to Stabler, “my theory is that I have a theory.” Stabler offers to come over. “My theory,” she says, “my theory is that there is no God.” The children’s bells ring so furiously that Benson can’t even hear Stabler’s reply over the din. When Stabler comes over and lets himself in with the spare key, he finds Benson bent over the toilet, heaving, crying.",
 "“It’s the whole city,” Benson says to herself as she drives. She imagines Stabler in the seat next to her. “I’ve been all over. It’s the whole fucking city. The heartbeats. The girls.” She clears her throat and tries again. “I know it sounds crazy. I just have a feeling.” She pauses, then says, “Stabler, do you believe in ghosts?” Then, “Stabler, do you trust me?”",
 "Stabler finds the police report for his wife’s rape. It’s so old that he has to call in a favor from a guy in the records department. The sound of the paper scraping against the thin manila envelope slows Stabler’s heart.",
 "Stabler and Benson respond to a report of a rape in Central Park. When they get there, the mutilated body has already been taken to the medical examiner’s office. A confused junior cop is busy rolling yellow crime scene tape from tree to tree. “Weren’t you just here?” he asks them.",
 "Benson and Stabler grab beers at a pub down the street from the station. They hold the frosted mugs in their hands, leave handprints on the glass that look like angels. They say nothing.",
 "  ",
 "Abler and Henson respond to a report of a rape in Central Park. They examine the mutilated body. “Cult,” says Abler. “Occultists,” says Henson. “A cult of occultists,” they say in unison. “Take the body away.”",
 "Henson sleeps through every night. She awakes refreshed. She eats a bagel with cream cheese for breakfast, and with it a mug of green tea. Abler tucks in his kids and spoons his wife, who laughs in her sleep. When she wakes, she relates to him the very funny joke from her dream, and he laughs, too. The children make pancakes. The hardwood floors are flooded with pools of light.",
 "For three days in a row, there is not a single victim in the entire precinct. No rapes. No murders. No rape-murders. No kidnappings. No child pornography made, bought, or sold. No molestations. No sexual assaults. No sexual harassments. No forced prostitution. No human trafficking. No subway gropings. No incest. No indecent exposures. No stalking. Not even an unwanted dirty phone call. Then, in the gloaming of a Wednesday, a man wolf-whistles at a woman on her way to an AA meeting. The whole city releases its held breath, and everything returns to normal",
 "Abler and Henson are sleeping together, but no one knows. Henson is the best lay that Abler’s ever had. Henson’s had better.",
 "“What are you doing here again?” the victim’s grandmother asks them. Benson looks at Stabler, and Stabler at Benson, and they turn, confused, back to her. “I already told you everything I know,” the old woman says, waving a gnarled hand at them dismissively. She slams the door so hard a flowerpot jumps off the porch railing and lands in the lawn. “Did you come and see her?” Benson asks Stabler. He shakes his head. “You?” he asks her. Inside, a Mills Brothers record starts up with pops and scratches. Shine little glow-worm, glimmer, glimmer. “No,” Benson says. “Never.”",
 "Abler’s sons bring home perfect grades and don’t even need braces. Henson’s many lovers bring her to increasingly ascending levels of ecstatic transcendence vis-à-visthe clitoris, vis-à-vis asking her what she wants, yes, what she, yes, what, yes yes yes fuck yes.",
 "The bells ring, ring, ring through the night, the peals stripping skin from Benson’s body, or that’s how it feels, anyway. Faster, faster, go faster. “I need to sleep,” Benson says. “I need to sleep to go faster.” That makes no sense. We never get to sleep. We never sleep. We tirelessly pursue justice at all hours. “Don’t you remember needing sleep?” Benson asks wearily from her unwashed sheets. “You were human, once.” No no no no no no no no.",
 "There are so many notches in Benson’s headboard—so many successes, so many failures, maybe she should have kept them apart?—the wood looks like it’s been chewed away by termites. When the two-tone beat sounds, the chips and shavings tremble on her carpet and nightstand.",
 "“Five-year-olds murder six-year-olds,” Benson says dully, the skin beneath her eyes dusky ash from lack of sleep. “People are monsters, and we are all lambs just waiting to be killed. We are monsters and victims at the same time, and only experience will tip the scale one way or the other. This is the world we live in, Stabler.” She sips noisily on her Diet Coke. She tries to look away from Stabler’s wet eyes.",
 "Benson watches a lot of TV on her days off. She gets an idea. She spreads a line of salt along her threshold, on the windowsills. That night, for the first time in months, the bell-children stay away.",
 "Stabler rubs his wife’s shoulders. “Can we talk?” She shakes her head. “You don’t want to talk?” She nods. “You want to talk?” She shakes her head. “You don’t want to talk?” She nods. Stabler kisses her hair. “Later. We’ll talk later.”",
 "Abler and Henson solve their ninth case in a row, and their captain takes them out for celebratory steaks and cocktails. Abler gnaws down hunks of steak too big for his gullet, Henson polishes off one dirty martini after another. Ten of them. Eleven. A man on the opposite side of the restaurant, who has been nibbling bird-like on a Caesar salad, begins to choke. He turns blue. A stranger delivers the Heimlich, and a half-chewed wad of meat lands on the table of a lifelong teetotaler who is starting to feel a little strange. “I feel like I’ve had twelve drinks,” she says, giggling, hiccupping. She has. Henson drives Abler home, and they laugh. Thirteen blocks from the restaurant, they grope at each other, kissing as they stumble out of the car. Henson puts Abler’s hand on her breast, and her nipple tightens",
 "Some crazy person keeps leaving sacks of perfectly good produce in a trashcan. Henson frequently finds herself pulling it out, taking it home, scrubbing the beets good and hard. How crazy. What a weird thing to go to waste.",
 "The gunman lets all of the hostages go, including himself.",
 "Benson is lonely without the bells. Her apartment is so quiet. She stands in her doorway, staring down at the white line. She takes her big toe and probes it. She remembers being at the beach with her mother when she was a child and burning her feet on the hot, smooth sand. She pushes her toe, breaking the line, and says, “Oops,” but doesn’t really mean it. The children come rushing at her like a flash flood rolling through a narrow gorge. Their bells ring chaotic, gleeful and rapturous and angry, like a swarm of euphoric bees. They tickle her skin with their desperation. She has never felt so loved.",
 "You are the only one we trust, the bell-children say to Benson. Not that other one. Benson assumes they mean Stabler.",
 "Abler and Henson notice the bullet casing buried in the dirt. They notice the smear of blood near the doorframe, the orientation of the street. They look at each other and know that they’re each calculating the sunlight on this avenue at the time of the crime. By the time they get inside, they know to arrest the wife. They don’t even have to ask her any questions.",
 "“If you are dead, you can see everything,” Benson says to the bell-children. “Tell me who the doppelgängers are. Why are they so much better at everything than me and Stabler? Tell me, please.” The bells ring and ring and ring.",
 "Benson sees Henson coming out of the precinct. Her stomach gnarls. The same face, but prettier. The same hair, but bouncier, somehow. She must find out what kind of product she uses. Before she kills her.",
 "“You’re a lunatic,” Henson says, struggling against the handcuffs, and ropes, and chair, and chains. Benson leaves Stabler another message. “My partner is going to come and get me, you’ll see,” Henson says. “He’ll come for me.”",
 "“Stabler will come and back me up. He knows what you’ve been doing. Stealing our cases. Pretending to be us.”",
 "Stabler pulls out his cell phone as the ringtone dies. 14 New Voicemails. He can’t do it, he can’t. The phone buzzes in his hand like an insect. 15. He turns it off.",
 "Abler comes for Henson. Of course he does. He loves her. Benson watches as he gently unties the ropes, unwraps the chains, unlocks the handcuffs, and lets her stand up from the chair on her own. Benson is holding her gun in her hand. She unloads three bullets into each of them, not expecting much. They keep moving as if nothing is happening except the funny foxtrot of their feet.",
 "“Detective, how can you not account for bullets missing from your gun? What are you listening to? Benson! […] No, I can’t hear it. […]There’s no sound, what are you talking about?”",
 "“Father Jones,” Benson says, her forehead pressing into the rough carpet in his foyer, “something is really wrong with me.”",
 "  ",
 "Miles away from the precinct, a teenage boy and his seven-year-old sister drop dead in the middle of their walk home from school. When they are autopsied, bullets are pulled from the purple meat of their organs, though there are no entrance wounds on either of their bodies. The medical examiner is baffled. The bullets clink clink clink clink clink clink in the metal dish.",
 "The DA laughs and laughs. She laughs so hard she coughs. She laughs so hard she pees a little. She falls down onto the floor and does a little half-roll, still laughing. There is a knock on the bathroom door, and Benson pushes open the door uncertainly. “Are you all right? The jury has come back. Are you…are you okay?”",
 "“Your mother has called five times in the last two days,” Stabler’s wife says to him. “Please call her back so I can stop making excuses for you.” Stabler looks up from his desk, where the manila envelope is resting, so anemically thin he wants to scream. He looks over at the mother of his children, the hollow at the base of her throat, the fine fringe of her eyelashes, the fat zit on her chin that she is probably minutes from popping. “I need to talk to you,” he says.",
 "“You have to understand,” says Father Jones. “I loved her. I loved her more than I have loved everything. But she was sad, so sad. She couldn’t bear to be here anymore. She saw too much.”",
 "Father Jones shows Benson how to pray. She clasps her hands together like a child, because that is the last time she’s tried it. He talks about opening her mind. She pulls her knees up to her chest. “If I open my mind any further, they’ll crowd out everything.” When he asks her what she means, she just shakes her head.",
 "“I made it up,” the woman says dully. Benson looks up from her yellow legal pad. “Are you certain?” she asks. “Yes,” the woman says. “Start to finish. I certainly made it up from start to finish.”",
 "Outside of the courtroom, protesters shove and shout, the wooden dowels of their signs knocking noisily against one another. It sounds like percussion. The worst percussion. Benson and Stabler use their bodies to shield the woman, who sobs and shuffles. Benson looks left, looks right. Shots. The woman crumples. Her blood runs down a storm drain, and she dies with her eyes half-open, an interrupted eclipse. Benson and Stabler feel the beat at the same time, down beneath the pavement, beneath the screaming and the panicked crowd and the signs and the woman dead, dead, there it is, the one-two, and they look at each other. “You can hear it, too,” Stabler says hoarsely, but before Benson can answer, the shooter takes out a protester. Her sign falls facedown in the blood.",
 "The DA rolls down the hill in her dreams, stumbling, tumbling, rumbling down, down in the deep. In her dream, there is thunder, but the thunder is the color of rhubarb and it comes in twin booms. Every time the thunder sounds, the grass blades change shape. Then, beneath her body, the DA sees Benson, lying on her back, touching herself, laughing. The DA dreams her clothes off, and dreams herself rolling her body against Benson’s, and the thunder rolls, too, except not really, it’s more walking. Dum dum. Dum dum. Dum dum.  In the afterburn of the dream, she is alone in her bed, and the window is open, the curtains fluttering in the breeze.",
 "“Why did you look it up?” Stabler’s wife asks. “Why? All I wanted was to bury it. I want it to be hidden. Why did you do it? Why?” She cries. She pummels her fists into a giant, overstuffed throw pillow. She begins to walk from one end of the room to the other, holding her arms so tightly to her torso that Stabler is reminded of a man who once came to the precinct, covered in blood. He held his arms like this, too, and when he let them drop, his wounded abdomen opened up and his stomach and intestines peeked out, like they were ready to be born.",
 "“Hey,” Benson says to the DA, smiling. The DA’s hands squeeze tightly into themselves. “Hi,” she says quickly before spinning on her heel and walk-running in the opposite direction.",
 "The girl staggers into the precinct with nothing on her body but a burlap sack. She tries to talk, but the words that come out are nonsense. Stabler gives her a cup of water. She drinks it in a single gulp, and then vomits onto his desk. The contents: said water, four nails, splinters of plywood, and a laminated slip of paper with a code on the side that seems to indicate it came from a library book. She keeps talking. Words tumble out, but in an order that makes no sense. The words are long, and real, Stabler discovers, flipping through a dictionary. But the sentences make no sense. None at all.",
 "Stabler only ever wanted daughters when he first married his wife. He’d had a brother. He knew. Now, he is paralyzed with fear for them. He wishes they were never born. He wishes they were still floating safely in the unborn space, which he imagines to be grayish-blue, like the Atlantic, studded with star-like points of light, and thick, like corn syrup.",
 "Stabler’s wife has not spoken to him since the manila folder. She chops vegetables with a large knife, and he would rather she stick it in his gut than continue the sparking silence. “I love you,” he says to her. “Forgive me.” But she keeps chopping. She puts clean slits in the stippled plastic cutting board. She lops off the heads of carrots. She undoes the cucumbers.",
 "Benson goes to a New Age shop in the Village. “I need a spell,” she says to the proprietor, “to find what I am seeking.” He taps a pen against his chin for a few moments, and then sells her: four dried beans of unknown origin, a small white disk that proves to be a sliver of rabbit bone, a tiny vial that appears empty—“the memory of a young woman losing her virginity,” he says—a granite basin, a wedge of dried red clay from the banks of the Hudson.",
 "Stabler invites Benson over to his house for Thanksgiving. Benson offers to help pull the guts from the turkey, something she always wanted to do as a child. Stabler’s wife gives her a bright orange bowl, leaves to attend to her squabbling daughters. Benson notices that Stabler’s wife is not speaking to Stabler. She sighs, shakes her head. Benson sticks her hand deep into the turkey’s guts. Her fingers push through gristle and meat and bones and close around something. She pulls. Out of the turkey comes a string of entrails, on which are suspended tiny bells, slick with blood. The meal is a great success. There is a photo of it on Stabler’s hard drive. Everyone is smiling. Everyone is having a very nice time.",
 "Benson and Stabler go to the New York Public Library. They show the feral girl’s photo to the librarians. One of them says she doesn’t know her, but her eyes drift upwards when she says this. Benson knows that she is lying. She follows the librarian to the break room and shoves her up against a vending machine. Inside, bags of chips and pretzels rustle. “I know you know her,” Benson says. The woman bites her lip, then takes Benson and Stabler down to the basement. She pushes open a metal door to an old boiler room, from which hangs a broken padlock. A cot stands against a far wall, stacks and stacks of books make a tiny metropolis all over the floor. Benson flips open a cover, then another. All of them have a red stamp: WITHDRAWN. The librarian pulls the gun out of Stabler’s holster. Stabler shouts. Benson turns around just in time for a fine red mist to paint her skin.",
 "“How could you possibly let her get your gun?!” Benson yells at Stabler. “How could you be looking at books when there was an insane kidnapping librarian in the room?!” he yells back at her. “Sometimes,” she starts angrily, but her voices trails off.",
 "The captain takes the last photo down from the bulletin board. He wants a drink more than he has in many years. “All it would have taken,” he says, his voice rising with every syllable, “for ONE WOMAN to survive would have been my detectives not being ASLEEP,” here he slams the photo down on the desk with more force than had actually killed her, “on the JOB.” Benson looks down at her legal pad, where she had anagrammed and anagrammed the serial killer’s clue, never succeeding.",
 "This is how it went. The girl was sick with prophecy. She touched the arm of young Ben Jones, later to be Father Jones, before she knelt herself to death off a Brooklyn rooftop. He carried it inside of his body for decades. Stabler was the one to restrain him when he freaked out during Mass, and now had it, too. He sees his daughters, projected into their terrifying futures. He sees his wife, living long and always remembering. He cannot see Benson, though. Something shades his vision. She is smoke, elusive.",
 "Stabler is grocery shopping with his oldest daughter when he sees a man picking up apples, examining them closely, and setting them back down on the pile. He recognizes him. The man looks up. He recognizes Stabler, too. He calls him by his first name, except it’s not his first name, really. “Bill!” he says. “Bill!” He looks at Stabler’s daughter. Stabler grabs her arm and pulls her into the next aisle. “Bill,” the man says, sounding excited, knocking over a display of corn tortillas. “Bill! Bill! Bill!”",
 "A man in a ski-mask robs a bank with a plastic gun and gets fifty-seven dollars. The teller saves the day by slicing off his face with the machete that he keeps under his counter.",
 "“Don’t you worry,” the gynecologist says to Stabler’s wife. “This isn’t going to hurt one bit.”",
 "Benson decides to try the spell. She combines the ingredients like the man had shown her. She crushes the beans and the bone. She uncorks the bottle. “Tip it fast,” he’d told her, “and catch it under your pestle, or else it’ll float up and away.” She turns the bottle toward the mortar, but suddenly her brain convulses and she is remembering something that never happened, a screaming, burning pain, a dark room lined with windows, curtains drawn, a cold, black table. She stumbles blindly backwards and knocks over the mortar and pestle. She falls to the floor and trembles, shakes. When it finally passes, she sees the girl-with-bells-for-eyes staring back at her. Ringing back at her. The first of many times, she says. All night, Benson dreams, dreams, dreams.",
 "One afternoon, at her desk, Benson feels the telltale tickling. She shifts in her chair. She crosses and uncrosses her legs. On the way home, she stops at the drugstore on the corner. In her bathroom, she squats. She walks carefully to her bed and gets horizontal. She feels the bullet melting inside of her, making her better. The girl-with-bells-for-eyes comes to the side of her bed, bells swinging wildly like she is a church caught in a stiff wind. Come on. “I can’t.” Why not? “I can’t get up. I can’t move. I can’t even cough.” What is happening to you? “You wouldn’t understand.” Get up. “I can’t.” The core of her is soothed and calmed and she cannot move or else everything will come out. The girl-with-bells-for-eyes gets as close to the bed as she can without walking through it. She begins to glow. Benson’s bedroom is filling with light. Across the street, a man with a telescope lifts his head from the eyepiece, gasps.",
 "“Okay, so, here’s my theory,” Stabler says to Benson when she gets back into the car with the coffees. “Human organs. They are wet and thick and fit together like pieces of a puzzle. It’s almost like someone zipped open human skulls before birth and slopped them in there like oatmeal. Except that’s not possible.” Benson looks at Stabler and squeezes her cup so hard a little fart of scalding coffee runs down her hand. She looks behind her. She looks back at him. “It’s almost like,” he says thoughtfully, “they were grown on the inside, and are meant to be shaped together.” Benson blinks. “It’s almost like,” she says, “we grow. In the womb. And keep growing.” Stabler looks excited. “Exactly!” he says. “And then, we die.”",
 "  ",
 "Stabler’s daughters get into a fight over a bowl of soup. When Stabler gets home, the oldest daughter has an ice pack on her forehead and the youngest is kicking her feet above the tiled kitchen floor. Stabler goes into the bedroom, where his wife is lying on her back, staring at the ceiling. “They’re your daughters,” she says to Stabler. “Not mine.”",
 "Benson and Stabler don’t play Monopoly anymore.",
 "Benson buys twice as much produce as normal, and doesn’t even wait for it to rot. She throws a ripe vegetable in every garbage can in a twenty-block radius. It feels good to spread it out like this, the wasting",
 "After the body is removed, Benson and Stabler stand around the dried pool of blood. A policewoman comes into the bedroom. “The landlord is outside,” she says. “He wants to know when he can get to cleaning the apartment up for rental.” Benson pokes the stain with her foot. “You know what’d get this out?” Stabler looks at her, his eyebrows knit. “OxiClean™. It’d get this stain right out” she continues. “You could rent this place next week.” Stabler looks around. “The landlord isn’t here yet,” he says, slowly. “OxiClean™ would get this right out,” she says again.",
 "Only after the sixth small black girl goes missing does the police commissioner finally make a statement, interrupting the season finale of a popular soap opera. The enraged letters start coming soon after. “Are you going to tell me if Susan’s baby belongs to David or not, Mister Police Commissioner??????” says one. Another person sends anthrax.",
 "The drumming won’t stop. Stabler considers that it is his conscience making that horrible, horrible sound.",
 "Benson likes her Tuesday night date too much to go home with him.",
 "Father Jones prepares to deliver the Eucharist. The first people in line look like Stabler and Benson, except different. Wrong, somehow. When he lays the wafer on the first’s tongue, the man closes his mouth, smiles. Father Jones feels forgiveness melting down the back of his own throat. The woman, then, too, takes it, smiles. Father Jones almost chokes this time. He excuses himself. In the bathroom, he rocks back and forth on his feet clutching the counter and weeping.",
 "Stabler works out three times a day, now. He insists on jogging to crime scenes instead of using the squad car. Whenever he takes off from the station, his button-down and tie tucked into bright red running shorts, Benson goes and gets herself a coffee from the bodega, reads a newspaper, and then drives to the crime scene. Stabler always arrives a few minutes later, his fingers pressed against his pulse, shoes striking the pavement in an even rhythm. He jogs in place while they interview witnesses.",
 "On the subway, Benson thinks she sees Henson and Abler on a train running the opposite direction. They blast past each other in a blaze of butter yellow light, the windows flashing by like frames on a filmstrip, and Henson and Abler appear to be in every one, moving jerkily like they are rotating through a phenakistoscope. Benson tries to call Stabler, but there’s no signal below the earth.",
 "Benson stays home with swine flu. Her fever reaches 103º; she hallucinates that she is two people. She reaches over to the opposite pillow, years empty, and feels for her own face. The girls-with-bells-for-eyes try to make her soup, but their hands pass through the cupboard handles.",
 "Stabler offers to take the girls out for Halloween. He goes as Batman, buys a hard plastic mask. The girls roll their eyes. Before they go out, his wife faces him. She reaches up and snatches the mask off his face. He seizes it back from her and slides it back on. She pulls it off again, so hard the band snaps and catches his face. “Ow,” he says. “What are you doing that for?” She shoves the mask into his chest. “Doesn’t feel very nice, does it?” she hisses through clenched teeth.",
 "The man takes out his rifle, braces it against his good shoulder, and squeezes the trigger with all the seductive force of a beckoning. The bullet strikes the missing woman’s neck, and she goes down, loosed of her life before she lands in the leaves and sends them up like ashes.",
 "The man lets out another sobbing woman. As she begins to run for the woods, he realizes he’s tired and wants to go make some dinner. He takes a few steps toward the tree line, and she joins her sister.",
 "“I choose this life,” the prostitute says to the social worker with the worried eyes. “I do. Please put your energy into helping girls who aren’t here by choice.” She is so right. She is murdered, anyway.",
 "A prostitute is murdered. She is too tired to become a spirit.",
 "A prostitute is murdered. She is too angry to become a spirit.",
 "A prostitute is murdered. She is too sad to become a spirit.",
 "The girl-with-bells-for-eyes—the first one who had sought Benson’s sour sleep breath and twitching eyelids all that time ago—comes into Benson’s bedroom. She walks into the bed. She takes her fingers and presses them into Benson’s mouth. Benson does not wake up. The girl pushes herself, in and in, and when Benson’s eyes open, Benson is not opening them. Benson is curled up in the corner of her mind, and she sees through her eyes distantly, like they are windows on the opposite side of a lengthy living room. Benson-who-is-not-Benson walks around the apartment. Benson-who-is-not-Benson takes off her nightgown and touches her grown woman’s body, inspecting every inch. Benson-who-is-not-Benson puts on clothes, hails a cab, and knocks on Stabler’s door, and even though it is 2:49 a.m, Stabler does not look even a little bit sleepy, though he is confused. “Benson,” he says. “What are you doing here?” Benson-who-is-not-Benson grabs his t-shirt in her hand and pulls him toward her, kissing him with more force and hunger than Stabler has ever felt in his own mouth. She releases his shirt. Benson cries into the darkened walls of her own skull. Benson-who-is-not-Benson wants more. Stabler wipes his mouth with his hand and then looks at his fingers, as if expecting to see something. Then he shuts the door. Benson-who-is-not-Benson returns to her apartment. Benson looks up from her knees to see the girl-with-bells-for-eyes standing in front of her. “Who is driving?” she asks thickly. The bells ring. No one. And indeed, Benson’s body is lying heavy as an unanimated golem on the bed. The bells ring. I’m sorry. The girl-with-bells-for-eyes sinks her fingers into Benson’s head, and",
 "Benson wakes up. Her head is throbbing. She rolls over onto the cool side of the pillow, her dream ebbing away from her like a rubber duck bobbing gently out to sea.",
 "The butcher takes a hose to the floor, and the blood spirals and sinks down the drain. It wasn’t animal blood, but he has no way of knowing what it was his assistant was cutting up. The evidence is destroyed. The girls remain lost forever.",
 "“Is it me, or is this steak kind of gamey?” Benson’s date says to Benson. She shrugs and looks down at her scallops. She prods one with a knife and it parts a little in the center, like a mouth opening, or worse. “It’s just… a weird flavor,” he says. Another bite. “But good, I guess. Good.” Benson can’t remember what he does for a living. Is this their second date, or their third? He chews with his mouth open. She invites herself to his apartment.",
 "Stabler takes another long pull of his whiskey. He slumps in his armchair. Upstairs his wife sleeps, sleeps, dreams, wakes up, sleeps more, hates him, wakes, hates him, sleeps. He thinks of Benson, the way she stood there, the way her clothes looked put on funny, the way she drank from him like she was dying of thirst, the dreamy way her hand ran over the metal fence, over the iron-tipped gate like she was asleep, like she was high, like she was a woman in love, in love, in love.",
 "  ",
 "Shadows pass over the marbled halls of justice, through the police station, across crowded and empty streets. They slide up walls and through grates and under doors and arc through glass windowpanes. They take what they want, leave what they want, and some cry, and some don’t. Life is created and destroyed. Mostly destroyed.",
 "“If this child is part of The Plan, then The Plan was that I would be raped. If this child is not part of The Plan, then my rape was a violation of The Plan, in which case The Plan is not a Plan at all, but a Polite fucking Suggestion.” Benson reaches out for her, but the woman looks down at the water, kneels from the railing, and is gone.",
 "“Look, it’s just that I’m walking around feeling like I’m going to vomit out my own toenails, and I want to die, and I want to kill someone, sometimes, and I feel like I’m on the verge of dissolving into a puddle of organs and slop. Organ slop. “Um, that’s…that’s…I’m sorry. Look, I just called to report a vandal in my neighborhood.”",
 "They find the actress hours after her disappearance, tied to the mast of a ship in New York Harbor, a reproduction musket laced between the coils of rope and wedged between her voluminous breasts. Her Renaissance Faire corset is half-unlaced, her shirt torn. He wanted her to fight back, she tells Stabler. He wanted her to slap him, and call him a scoundrel, and then to marry him. He called himself Reginald.",
 "Benson gets the flu. She vomits up: spinach, paint shavings, half a golf pencil, and a single bell the size of her pinky nail.",
 "At Benson and Stabler’s favorite sushi restaurant, they have stopped using plates and started using models. Benson pinches a red swatch of tuna from the hipbone of a brunette who seems to be trying very hard not to breathe. The owner stops by the table, and seeing Benson’s frown, says, “Cheaper than plates, you know.” Stabler reaches for a piece of eel, and the model takes a sudden breath. The meat eludes his chopsticks—once, twice.",
 "All over the city, pedestrians stop mid-stride, a small weight lifted from bodies, a memory snuffed. A barista, marker poised over a cup, asks a man the same question in ten seconds. He stares at her, blinks. “I don’t know,” he says. In graves and ditches, in morgues and mortuaries, in rushes and bogs, dipping and rolling on the skins of rivers, names trace the bodies of the dead like flames along kindling, like electricity. For four minutes, the city becomes filled with the names, with their names, and though the man cannot tell the barista that Sam wants his latte, he can tell her that Samantha is not coming home but she is somewhere, though she is nowhere, and she knows nothing, and everything.",
 "Stabler tries to convince his oldest daughter to eat something, anything. She takes the paper napkin in seven small bites.",
 "After the girls are asleep, Stabler sits next to his wife, who is cocooned under the blankets of their bed. Even her face is swaddled. Stabler gently pokes at the opening in the comforter, and soon the tip of her nose is revealed, a heart of skin around her eyes. She is crying. “I love you,” she says, “I do. I am so angry with you. But I do love you.” Stabler takes her into his arms, her whole cloth burrito self, and rocks her in his arms, whispering sorry, sorry into her ear. After he turns out the light, she asks him to cover her face again. He lays the tucked bits back over her, lightly.",
 "The air roils. The clouds rush at the city as if they have been waiting.",
 "A new police commissioner rides into town. He makes big promises. His teeth are the color and shape of Chiclets, too even. Stabler keeps trying to tally the number of teeth that show when the police commissioner smiles for the camera, but he loses count every time.",
 "When the girls-with-bells-for-eyes come to Benson’s door, they are silent. When Benson finally opens the door to go to the gym, they are there, filling the hallway. Their bells rock, but no sound comes out. When Benson gets close, she realizes that someone has unhooked the hammers. The bells swing back and forth and back and forth, and they are quieter than they have ever been.",
 "Stabler takes his wife dancing. He is surprised that she agrees. Past the doors of the salsa club, she is lithe and hot, sweating, spinning. He has not seen her this way since they were young, since just before they were married. The glaze of sweat and the smell of her turns him on, cracks open his want in a way that he’d forgotten existed. They dance close. She slides her hand down the front of his pants, bites her lip, kisses him. Deep inside his body, something beats. Dum dum, dum dum. A heartbeat, almost. Even. They take a cab home, and in their bedroom rip her dress getting it off, and they have not done this in years, this, this, and she digs her nails into his back and whispers his name, and they have not been like this since those years before, since that time long ago, before before, but after. He calls her name.",
 "The precinct’s interns sense that something has changed between Benson and Stabler, but they don’t know what. They track their movements in a repurposed notebook from a biochem class. They take photos of them with their cell phones. They sprinkle Spanish fly into the coffee machine. They summon a demon with blood from their own bodies and ash from a cathedral votive and a squirrel bone and white chalk and bundles of dried sage. They beg the demon for his help. Annoyed, he takes one of them back to hell with him, punishment for making him come so far.",
 "“Lucy, do you know where Evan is?” Stabler asks her. “He’s never this late.”",
 "“Lucy, do you know where Evan is? He’s never missed biochem before.”",
 "Benson drains her coffee. Her mouth burns a little. She feels woozy. She lies down in the back room.",
 "In her dream, Benson hears the heartbeat. She is on an empty New York City street. There is no breeze. The pavement does move, though, like something is breathing. Benson begins to follow the sound of the heartbeat, down the street. She sees a dark doorway, a sign above it that reads “Shahryar Bar & Grill.” Inside, the counters are polished and gleam dark red. The bottles and glasses gleam like the surface of a river, and every time the sound comes they shake slightly. There is a door tucked in the corner, a strip of light glowing beneath it. Laughter. Benson thinks it sounds like it did when she was a girl, and her mother had a cocktail party and Benson had to sit in her bedroom, a plate of tiny appetizers and half a cup of apple juice resting on her nightstand. She nibbled a mushroom that was full of something melted, and then drank her juice, and she could hear laughter on the other side of the door, glasses clinking, voices going loud and soft and loud again. She tried to read a book but ended up in her bed in the dark, listening to the voices that were so far and so close, picking out her mother’s bray in the din like pulling a loose thread of elastic from the band of your underpants, pulling, tightening, ruining them. That is what she feels now, the voices on the other side of the door. She reaches for the handle, the distance between her hand and it halving with each passing nanosecond, the metal cold even before her hand touches it. When Benson wakes up, she is screaming.",
 "“Just one more bite,” Stabler begs his oldest daughter. “Just one, baby. Just one carrot. Let’s start with one carrot.” He sees her being carved away, the way the wind shapes a dune into nothing. “One. Just one.”",
 "Benson Googles. <<dead girls bells eyes missing hammers>> <<girls bells eyes>> <<girl ghost bells eyes>> <<ghosts broken>> <<what happens if I see a ghost?>> <<what makes a ghost?>> <<ghost fixing>> For months, the ads in her browser try to sell her: brass bell sets, ghost hunting equipment, video cameras, CDs of bell choirs, dolls, shovels.",
 "The new police commissioner looks up from his blotter. Across from him, Abler and Henson are not taking notes. They have perfect memories. “Make it so,” says the new police commissioner. “Make it so.”",
 "  ",
 "Benson is sure that her smartphone is smarter than she is, and she finds it deeply upsetting. When it gives her information, she puts it close to her face, says “NO,” and does the opposite.",
 "The DA watches the hour and minute hands pinching time between them. When the judge asks her if she has any questions for the witness, she shakes her head. At home, Henson is waiting for her, curled up on the couch with a copy of Madame Bovary, chewing on a piece of hair, laughing at all the right places. They make dinner together. They watch the rain.",
 "A story is delivered over and over again on the 24-hour news channels. Tainted vegetables, they say. Bok choy, broccoli, celery, Brussels sprouts, all tainted, dirty, bad, wrong. Benson catches the tail end of a report as she forks stir-fry straight out of the pan. “Return produce to your local stores for a full refund,” the reporter says, looking grave. Benson looks down at the pan. She finishes every scrap of green. She goes to her fridge and begins to prepare more.",
 "“Dad,” says Stabler’s youngest, “who is Uncle E?” He looks up from his newspaper. “Uncle E?” “Yes,” she says. “A man came up to me after school today. He said his name was Uncle E and that he was my uncle.” Stabler hasn’t spoken to his younger brother, Oliver, in ten years. He’s pretty sure Oliver still lives in Bulgaria. “You shouldn’t talk to strangers, baby,” Stabler says. “We’re going to have Mom walk you home from school from now on.”",
 "At the courthouse, Stabler looks up from the bathroom sink and sees Abler standing behind him. Abler smirks. Stabler swings around, half-soaped fists raised. The bathroom is empty.",
 "“Look, Benson,” Henson says from the other end of the line. Her voice sounds tinny and far away, as if she is standing over Benson’s body while Benson dies. “The thing is, you are suffering. You don’t want to suffer anymore, do you?” Benson leans the earpiece harder against her shoulder, and the plastic casing slips along the grease of her unwashed face. She does not answer. “It’s just that,” Henson continues, “we could make this all stop, you know. The girls. The sounds. The wanting.” Benson looks up. Stabler is shuffling through a stack of folders, absently scratching his jaw, humming a catchy Latin beat under his breath. “All you have to do is bring him to us. Bring him to us, and we can all call a truce.”",
 "Benson traces the call to a warehouse in Chelsea. Once there, she and Stabler use bolt-cutters to get inside. The hallway is dark. A single lightbulb, the filament struggling to burn, hangs from the ceiling. Benson and Stabler pull out their guns. They grope along the walls with their free hands until they reach another door. A big room, now, big as an airplane hanger, empty. Their footsteps echo. Benson sees another door on the other side of the room. It looks different. The strip beneath it glows red. She can feel her heart knocking loudly in her chest. Dum dum. Dum dum. Dum dum. She realizes that the sound is bigger than she is, that it is coming from outside of her, around her. She looks at Stabler, panicked, and he looks confused. “Are you all right?” he asks her. She shakes her head. “We have to go. We have to go now.” He gestures to the door on the other side of the room. “Let’s check out that door.” “No.” “But Benson—” “No!” She grabs his arm, and pulls him. They erupt into the sunshine.",
 "The rapist is raped. The raped are rapists. “Some days,” the prison doctor says to a resident as they stitch up a torn rectum, “I wonder if the bars make the monsters, and not the other way around.”",
 "The courtroom. A hallway. Six doors. In and out of each set—detectives, police officers, lawyers, judges, the damned. People go in one set of doors and come out another. Benson and Stabler miss Henson and Abler every single time.",
 "“Let me tell you a story,” Henson whispers to the DA as they curl up in her bed, the air heavy with the smell of sex. “When it’s over, I’ll tell you what you want to know about Benson, about Stabler, about all of it. Even about the sounds.” The DA mumbles her assent, feeling drowsy. “The first story,” Henson whispers, “is about a queen and her castle. A queen, her castle, and a hungry beast that lives below.”",
 "Father Jones senses the demon, though he cannot see it. From his bed, he smells sulfur, he feels the evil sitting on his chest. “What do you want?” he asks. “Why are you here?”",
 "The forensic psychologist is asked to come in on a case involving a serial rapist and murderer who dismembers his victims like they are middle-school frog dissections. “It makes more sense to him than you might think,” he says evenly as he watches the man laugh from the other side of the double-sided window. Stabler frowns. He distrusts the psychologist’s judgment.",
 "Benson buys a thousand bells and removes their hammers. She tries to give them to the girls-with-bells-for-eyes, but the hammers don’t take. She tries drawing them on a piece of paper, but the ink runs when pressed into their faces. The girls crowd into her kitchen, so many of them, and so bright, that the neighbor that spies on Benson with his telescope is certain that her apartment is on fire, and calls the fire department. Benson sits in her wicker chair, her hands resting on her knees. “All right,” she says. “Come in.” And they do. They walk into her, one at a time, and once inside she can feel them, hear them. They take turns with her vocal cords. “Hello,” Benson says. “Hello!” Benson says. “This feels really good,” Benson says. “What should we do first?” Benson says. “Now, wait,” Benson says. “I’m still me.” “Yes,” Benson says, “but you are legion, too.” In the distance, sirens tear up the night.",
 "“Did you know that Evan was kidnapped?” Benson asks the captain. He taps his sobriety coin on the varnished wood. “Who’s Evan?” “The intern! The intern. The intern that used to sit at that desk!” She points at Lucy, who is weeping softly in her rolling chair. Every sniffle pushes her back a millimeter until she is almost in the hall.",
 "Benson promises Lucy that she will look for Evan. She visits all of his normal haunts. The girls crowd in her head, talk to her. “He’s not here,” they say. “He’s Elsewhere. He’s swallowed.” When Benson tells Stabler about her search, he sighs deeply. “He’ll get spit up somewhere,” he says knowingly. “Just not here.”",
 "Evan the intern was annoying everyone in hell, so the demon sent him back. He overshot his target, though, and accidentally deposited him in Pennsylvania. Evan decides to stay. He never liked New York anyway. Too expensive. Too sad.",
 "Father Jones absolves the blooming trees and flowers. As their pollen is carried off, and begins to clog people’s lungs, Father Jones smiles. The coughs of redemption.",
 "Lucy the intern looks down at the slip of paper in her hand, where Benson had scribbled Father Jones’s address. When she looks up again, the front door opens, and Father Jones leans against the frame, looking exhausted. “Come in, child,” he says. “It seems we have a lot to talk about.”",
 "Over the course of three weeks, five different people catch and cut open five different gators in the Everglades. Inside each belly, an identical left arm—sparkling purple jelly bracelet, chipped green polish, thin white scar where the pinky meets the palm. When they run the prints, they trace the arm back to a missing girl in New York. The medical examiner looks at the five arms lined up next to each other. Spooked, she discards four of them. “Remaining body unrecovered,” she writes in her notes. “Victim presumed deceased.”",
 "Benson finally sits down and counts. She goes through files, paper and computer. She tallies, hatchmarks in groups of five, and covers pages and pages and pages. She goes home, flipping the blade out of her pocketknife as soon as the door closes behind her. She begins to dig into the kitchen table, the edges of the cupboards, counting, counting, counting, losing count, finding it again.",
 "Stabler pushes open Benson’s door. She is lying on the kitchen floor, arms outspread, facing the ceiling. Around her, the chairs and tables and footstool are all chewed to pieces. “There are so many of them,” Benson whispers. “So, so many.” Stabler kneels down next to her. He strokes her hair gently. “It will be okay,” he says. “It will be okay.”",
 "The DA calls in sick, again. “The sixty-fifth story,” Henson whispers into her ear, “is about a world which watches you and me and everyone. Watches our suffering like it is a game. Can’t stop. Can’t tear themselves away.”",
 "  ",
 "On a Tuesday, Stabler’s wife returns from the store to find a man who looks like her husband sitting on the stoop. He turns out his palms apologetically. “I lost my keys,” he says. She sets down the sack of groceries on the ground, fumbles for her own. She watches him out of the corner of her eye. He looks just like Stabler. His smile leaves the same tiny indent to the left of his mouth. But he is not her husband. Something in her brain is screaming: he is not her husband. The door swings open. Inside, her youngest comes out of her bedroom and wipes sleep from her eyes. She points to the man. “That’s Uncle E!” she shouts. Stabler’s wife grabs a heavy vase from the side table and whirls around, but he is already out the door, down the street, running full-speed, and then, gone.",
 "In the back row of the movie theater, Henson’s arm creeps over the DA’s shoulder. The DA looks at Henson’s face in the flickering half-dark. Here, more than anywhere, she looks just like Benson. She kisses her mouth.",
 "In the cop bar, Wilson Phillips plays. Stabler looks annoyed, but Benson grins at the memory from her adolescence. She mouths the words while training her eyes on her beer. She bobs her head at every mention of “reckless” and “kiss.",
 "The boy turns out lists and lists of the missing, dating back to before his birth, chronologically by the date of their disappearances. He draws thick black lines through most of them, though not all. His mother doesn’t understand the names, or the lines, and burns the lists on the grill in their backyard.",
 "When Stabler’s wife tells him about Uncle E, he instructs her to take the kids and go to her mother’s house in New Jersey. He sits on the stoop and waits for Abler to come back. He fantasizes about taking a brick to Abler’s head. His cell phone rings. “You think I’d ever visit the same place twice?” Abler purrs. Stabler tries to think, hard, about where Abler and Henson will be. But he cannot see. He cannot see at all.",
 "The DA kisses Henson, their twelfth hour of fucking, sleep, fucking, sleep. She hums promises into her ear. Father Jones shows Lucy how to keep demons away. Stabler stalks New York, searching for Abler, tense as piano wire, vibrating with rage. Benson takes herself and the girls inside her out on the town for dancing, for sweaty bottles of beer, to show them all a good, good time.",
 "Benson dreams that Henson and Abler seize her eyeballs and pull them out slowly, the nerve bundles stretching and drooping like Silly Putty.",
 "Stabler would just straight-up challenge them, but he doesn’t even know where to throw down his gloves.",
 "The dirty truth is, Benson doesn’t have a father.",
 "Without the interns to do their nefarious bidding, the gods turn to other tricks.",
 "All Benson knows is that she’s sure the street is breathing. The girls tell her what she needs to know. She is right to be afraid.",
 "Full of girls, Benson finds scrawling her own name to be almost impossible.",
 "I don’t care what the evidence says,” the judge chuckles. “You’re obviously innocent. Obvious! Get out of here, you.",
 "Stabler goes and visits his wife and daughters at his mother-in-law’s. He and his wife watch The Princess Bride with the girls. They both fall asleep before the end. On the couch together, piled high with pillows, dark but for the glow of the screen, Stabler and his wife look at what they have made.",
 "What have you learned?” the new police commissioner asks Henson and Abler. He is not a religious man, but the expressions on their faces so unnerve him that he crosses himself, which he has not done since he was a child.",
 "The DA steps out into the sunshine, blinking, shielding her face. She almost bumps into Benson, who is strolling down the sidewalk. Benson smiles at her. “Haven’t seen you around in a while. Have you been sick?” The DA blinks and reflexively wipes her mouth, catching the smear of lipstick that doesn’t belong to her. “Yes,” she says. “No. Yes, a little.",
 "Alone in his family’s house, Stabler drinks five old fashioneds. He is disturbed by how easy it is. He thinks about his daughters, his wife. His brother, suddenly, his baby brother. He struggles to remember his baby brother, who flits through his synapses like a sketch. Suddenly certain of something, Stabler runs out into the street and stares up at the sky. “Stop,” he begs. “Stop reading. I don’t like this. Something is wrong. I don’t like this.",
 "In a graveyard, Benson begins to dig. Her spine aches and her muscles freeze and twitch and burn. She digs up the first girl, then the second. She slides one coffin left, one coffin right. She drops them under their correct, respective names. Inside of her, two girls speak. “Thank you,” Benson says. “Yes, thank you,” Benson says. Her mind clears a fraction. She breathes. It is easier.",
 "Stabler meets Benson in her apartment. She is sitting in a pile of wood chips that used to be her kitchen table. She takes a long, languorous swallow of beer and smiles a watery smile. “My theory,” she says. “Our theory. Our theory is that there is a God, and he is hungry.",
 "  ",
 "“I am so tired,” the DA confesses to her boss. “I’m tired of losing cases. I’m tired of turning rapists back onto the street. I’m tired of winning, too. I’m tired of justice. Justice is exhausting. I am a one-woman justice machine. It’s too much to ask of me. Can we stage my death? Or something?” She does not tell the truth: she wants to see what Benson will do at her funeral.",
 "Stabler and his wife go for a walk, in New Jersey. They walk along a dirty beach—with shoes, so as not to cut their feet with broken bottles. “He locked me in the room,” she says to him. “He turned the lock and smiled at me. I couldn’t move. He hadn’t tied me up, but I couldn’t move. That’s the worst part. No excuse. You fight to put names on all of your dead, but not every victim wants to be known. Not all of us can deal with the illumination that comes with justice.” She dips her head, and he remembers the first time he met her. “Also,” she says softly, “you should know that Benson loves you.”",
 "Stabler pushes his youngest higher and higher. He thinks about what his wife said. “Off, Daddy! I said off!” He realizes she is shrieking at the top of her lungs. She, his daughter, not his wife. And certainly not Benson. Definitely not Benson.",
 "Benson doesn’t think about the moon very often, but when she does, she always undoes her top four buttons, tilts her throat up to the sky.",
 "An old woman kills a local deli owner. She tells Benson and Stabler that he raped her when they were teenagers. They don’t have the heart to tell her that he was a twin.",
 "All of the Hooter’s waitresses get pregnant at once. No one will say why. “This is not really a case,” Benson says, exasperated. Stabler doodles on his pad—a picture of a tree. Or maybe it’s a tooth?",
 "Deer, raccoons, rats, mice, cockroaches, flies, squirrels, birds, spiders, all of them, gone. Scientists take notice immediately. The state pours money into research. Where are they? Where did they go? What does it mean that they are missing? What would it take for their return?",
 "Benson likes her date, but the girls inside her screw it up by referring to themselves in the collective. “It’s the royal ‘we’!” she howls after his retreating back.",
 "Every night, Benson dreams about the girls’ deaths. She slips in and out of stabbings and shootings and stranglings and poisonings and gags and ropes and No, no, nos, all lucid, and cut with Benson’s normal dreams: sex with Stabler, apocalypses, teeth falling out, teeth falling out of Benson onto Stabler while they fuck on a boat as the Flood wipes everything away.",
 "The DA watches the 24-hour news networks for 24 hours.",
 "“What do you mean?” Stabler breathes into the phone. “Three birth certificates to Joanna Stabler in that ten-year stretch,” the receptionist says. “Oliver, you, and an Eli.” “I don’t have a brother Eli,” Stabler says. “According to this, you do,” she says, sucking noisily on a large wad of gum. Stabler hates it when people chew gum.",
 "Benson covers her apartment in flowerpots and long troughs full of black dirt, laying them among the destroyed remnants of her furniture, her list, her rules. She plants basil and thyme and dill and oregano and beets and spinach and kale and rainbow chard. The sound of pattering water released from a watering can is so beautiful she wants to cry. Time to make something grow.",
 "A tiny Dominican girl is taken off the street by a man in a grey coat. She is never seen again.",
 "Every time Benson flips her bedroom light on and off, she hears the sound. Dum dum. She feels it in her teeth.",
 "When she is tired, Benson lets the girls take over. They run her body all over town, buying hard lemonades and shimmying her chest at bouncers and, once, before Benson can take over again, kissing a busboy sweetly on his mouth, a mouth that tastes like metal and spearmint.",
 "She dances four nights a week for two years. He buys a ticket for every show, sits in the mezzanine, never goes backstage for an autograph. She always gets the uneasy sensation that she is being watched, aggressively, but never knows who it is.",
 "Father Jones sends Lucy the intern out into the world, infected as Stabler was. He kneels from the rooftop of his building, and takes the demon with him.",
 "“Yes,” Stabler’s mother says to him over the phone, carefully. “I did have an older son. Eli. But I haven’t seen him since you were a child.” “Where did he go?” Stabler asked. “Why did you never say?” “Some things,” she says, her voice thick with tears, “are better left unsaid.”",
 "The medical examiner can’t bring herself to admit that sometimes, she’s the one who wants to be cut open, to have someone tell her all of her own secrets.",
 "“I really care about you,” Stabler says. “And I know how you feel. I’m sorry that I’ve led you on. I’m sorry I haven’t been forthright. But I love my wife. We were going through a patch, but I love her. And I love my daughters. I should have told you after we kissed. I should have said that it wouldn’t go anywhere.” “We kissed?” Benson says. She probes her memories, and only comes up with dreams.",
 "“I mean, not…not everybody,” the constitutional scholar scoffed, looking equal parts amused and scandalized. “Can you imagine if everyone had those rights? Anarchy.” Abler smiles, and pours him another drink.",
 "Benson wakes up in the zoo again. She scales the wall, not caring that she trips the alarm, not caring that as she runs, cop cars are cruising, flashing, looking for her and only her. She is barefoot, her feet bleed, the street breathes, the street heats, the street is waiting, and what else is waiting? Beneath, beneath, beneath.",
 "  ",
 "Stabler listens to Benson. She tells him everything—the ghost girls and their now-silent bells—and things he already knows—the heartbeats from the ground, and its breathing, and her love. He looks around at the apartment full of plants, more greenhouse than home. “You’re saying they’re inside of you now.” “Yes.” “Right this minute.” “Yes.” “Do they tell you things?” “Sometimes.” “Like what?” “They say, ‘Ow, yes, no, stop it, that one, help us, there, but why, but when, I’m hungry, we’re hungry, kiss him, kiss her, wait, okay.…’ Also, I bought some bells.” She points to a ravaged cardboard box, overflowing with packing peanuts and glints of brass. Stabler frowns. “Benson, how can I help?”",
 "The handsome older gentleman folds his cloth napkin in half before dabbing his mouth. “What I’m saying,” he says to Benson, who can’t stop staring, “is that if this continues, I will expect you to quit your job. Naturally, you’ll be compensated above and beyond your current salary. I’ll just expect you to always be available.”",
 "Benson trims her plants, and bats away regret over saying “No.”",
 "Benson wakes up to see Henson standing over her bed. She is holding a garbage bag, and she is grinning. She dumps the contents over Benson’s bed, and they tumble out like ghostly river shrimp. The stolen hammers from the girls’ bells. They weigh nothing and yet Benson can feel them, somehow. Inside her head, the girls explode in chatter. When the points of light stop flashing in Benson’s eyes, she realizes that Henson has left. She tries to pick up the hammers, and they dissolve in her fingers like fog.",
 "The DA comes over to Benson’s apartment to talk about a case. “I like your greenhouse,” she says. Benson blinks, disbelieving. Then, she smiles shyly, offers to show her the plants. She shows the DA how to rewire a heat lamp. They laugh into the night.",
 "“You just gotta learn to live with it,” the bored officer says to the woman sitting in the chair across from him, shaking.",
 "Everyone on the web forum wakes up to find a jagged crack up the length of their bathroom mirrors.",
 "Abler and Henson reverse the stoplights, flood bathrooms, and steal the interior workings of all deadbolts.",
 "“You can’t stop me,” the note, pinned to the body, reads. “I control everything. —THE WOLF.” Benson and Stabler start a new file. Stabler cries.",
 "They can’t prove the naval officer was responsible because the evidence isn’t waterproof.",
 "The DA finally throws Henson out of her bed. “You’re not her,” she says, her voice heavy with sadness. “One more story,” Henson says, leaning against the doorframe. “Don’t you want to hear just one more? It’s a good one. It’s a real doozy.”",
 "If the day had been sunny and not overcast, she would have seen him coming. Everyone blames the weatherman.",
 "“It’s just that,” the guy says, pumping his head confidently, “my sense of humor is pretty subversive, you know? I, like, don’t submit to the P.C. brigade. I like to think of myself as a rebel.” For the first time in ages, Benson leaves her date. She’s desperate, but not that desperate.",
 "One night, Lucy knocks on Benson’s door. “Your gun,” she says. Benson frowns at her. “What?” Lucy seizes the gun from Benson’s holster. Benson makes a grab for it, but not before Lucy smears something on the handle. “A gift from Father Jones,” she says, handing it back to her.",
 "It’s been nice having her come around,” Benson says to her plants, referring to the DA. Benson hates diaries. “She’s really great company. Really great.” She imagines that the plants are arching toward her voice.",
 "There isn’t one. The DA can’t try the case.",
 "Stabler goes to visit his wife and children. He worries that Abler is following him. He stops his car. He drives back to New York. He takes a train. He hitchhikes to the house.",
 "Stabler’s wife curls against him. She breathes into his ear. “When do you think we can leave my mother’s place?” she asks. “When we catch Uncle E,” he says. He feels her face pull into a sleepy smile. “What do you think Uncle E stands for, anyway?” she asks blearily.",
 "Stabler tackles Abler to the ground. “I know who you are!” Stabler says into his ear. “You’re my brother, Eli. Uncle E, indeed.” Abler chuckles from beneath him. “No,” he says. “I’m not. I just called myself that to fuck with you. Eli died in prison, years ago. Your brother was a rapist. Your brother was a monster.” Benson pulls Stabler off. “Don’t listen to him,” she says. “Don’t.” Abler grins. “Do you want me to tell you who Henson is? She’s—”",
 "The hamburger doesn’t give a fuck who it kills.",
 "A girl is raped, murdered, and lit on fire. She comes into Benson’s head screaming, smoke curling off her burned skin, not understanding. It is the longest night of Benson’s life thus far.",
 "Abler and Henson sense what is coming. They fuck, they eat, they drink, they smoke. They go dancing, foxtrotting on the chairs; a gavotte across the finished walnut. When the Beasley family comes home, there are heelmarks in the soft wood of their dining room table, and half of the plates are broken.",
 "Copycat mischief-makers reverse street signs and tie people’s shoelaces together. When Stabler falls over a fifth time, he slams his fist down on his floor. “THAT. IS. IT.”",
 "“Don’t you understand?!” Abler howls as Benson and Stabler struggle to their feet. “We didn’t do this. This was not us. The women. All of the women.” Henson howls with laughter. “You thought this was all some vast conspiracy, but it’s not. The women—no, you’ve done them on your own. The heartbeat.” Benson pulls her gun from her holster and unloads a clip into both of them. Abler falls over immediately, an expression of surprise on his face. Blood gurgles from Henson’s mouth, drips in a long stream down her chin. “Just like in the movies,” Benson breathes.",
 "  ",
 "Without Henson and Abler, Benson and Stabler don’t know what to do with themselves. They go back, slowly, to old files. The missing girls and women. The dead. “Let’s get them out,” Stabler says, newly confident. “Let’s set them free.”",
 "“The reason we didn’t catch him before is because his alibi was foolproof. But now, we know.”",
 "They start responding to “no.”",
 "They arrest the madam who had permitted so many of her girls to be drowned. “Not by my hands!” she howls as they drag her to the squad car. “Not by my hands!”",
 "Benson doesn’t know how she knows, but she does. They walk the length of the Hudson. They locate eight missing bodies—different murderers, different years. She names them as the gurneys go rumbling past her.",
 "They catch the serial brander. His victims pick him out of a lineup, strange smiles pushing through their burned faces. “How did you catch him?” one woman asks Benson. “Good old-fashioned police work,” she says.",
 "“I’m looking for a wife,” Benson’s date says. He is handsome. He is brilliant. She stands up, folds her napkin on the table, and pulls three twenties from her wallet. “I have to go. I just…I have to go.” She runs down the street. She breaks a heel on her shoe. She skips the rest of the way.",
 "“No.” “Yes.” “No.” “No?” “No.” “Oh.”",
 "Benson plants some flowers.",
 "Benson and Stabler take out the kidnapper before he even reaches his destination.",
 "Benson and Stabler think they hear gunfire, but when they come bursting out of the diner, it’s just tiny fireworks lighting up windows three stories over their heads.",
 "“Not for much longer,” Benson says, to herself, in her sleep.",
 "Stabler and his wife dance all over the house, mouse masks on their faces. The girls stare at the scene in horror, and run to their rooms, where one is busy forgetting and the other is remembering what will, one day, be a chapter in her well-received memoir. Father Jones didn’t just touch Stabler and Lucy, you know.",
 "The DA comes and helps Benson sweep up the wood chips from her floor. They clean the windows. They order pizza and talk about first loves.",
 "The city is still hungry. The city is always hungry. But tonight, the heartbeat slows. They fly, they fly, they fly.",
 "On a Wednesday, they catch so many bad guys that Benson throws up seventeen girls in one afternoon. She laughs as they spill out of her, tumble into her vomit like oil slicks, and dissipate into the air.",
 "They chase. They catch. No one gets away.",
 "The last girl clings to the inside of Benson’s skull. “I don’t want to be alone,” Benson says. “I don’t, either,” Benson says, “but you need to go.” Stabler comes into Benson’s apartment. “Her name is Marcela Tietra. She was twelve. She was raped by her father, and her mother did not believe her. Her father killed her. He buried her on Brighton Beach.” Inside, the girl shook her head, as if to dislodge the sand in her hair. “Go,” Benson says. “Go.” The girl smiles and doesn’t, her bells barely rocking. “Thank you,” Benson says. “You’re welcome,” Benson says. There is a sound—a new sound. A sigh. And then, she is gone. Stabler hugs Benson. “Goodbye,” he says, and so is he.",
 "The DA comes to Benson’s door. Benson’s head, newly clear, feels like a vacant airplane hanger, a moor. Expansive, but empty. The DA reaches her hand up to Benson’s face, and traces her jaw with the barest weight. “I want you,” she says to Benson. “I’ve wanted you since the first time I met you.” Benson leans forward and kisses her. The heartbeat is a hunger. She pulls her inside.",
 "“In the beginning, before the city, there was a creature. Genderless, ageless. The city flies on its back. We hear it, all of us, in one way or another. It demands sacrifices. But it can only eat what we give it.” Benson strokes the DA’s hair. “Where did you hear that story?” she asks. The DA bites her lip. “From someone who always seemed to be right,” she says.",
 "Stabler and his wife talk it over. They decide to take the girls and go far, far away. “A new place,” he says, “where we can have any names we want. Any histories.”",
 "A bomb goes off in Central Park. It was beneath a park bench the whole time. No one is sitting on the bench when it detonates, and the only casualty is a passing pigeon. The serial killer sends a note to Benson and Stabler. All it says is “Oops.”",
 "Benson and the DA are both late to work, and smell like each other. Stabler sends in his resignation by express post.",
 "The DA and Benson roast vegetables on the grill, laughing. The smoke rises up and up, drifts over the trees, curls past birds and rot and blooms. The city smells it. The city takes a breath.",
 "",
 "",
};
String[] eptitle = {
 "Especially Heinous: 272 Views of Law & Order SVU",
 "Season 1",
 "Payback",
 "A Single Life",
 "Or Just Look Like One",
 "Hysteria",
 "Wanderlust",
 "Sophomore Jinx",
 "Uncivilized",
 "Stalked",
 "Stocks and Bondage",
 "Closure",
 "Bad Blood",
 "Russian Love Poem",
 "Disrobed",
 "Limitations",
 "Entitled",
 "The Third Guy",
 "Misleader",
 "Chat Room",
 "Contact",
 "Remorse",
 "Nocturne",
 "Slaves",
 "Season 2",
 "Wrong is Right",
 "Honor",
 "Closure: Part 2",
 "Legacy",
 "Baby Killer",
 "Noncompliance",
 "Asunder",
 "Taken",
 "Pixies",
 "Consent",
 "Abuse",
 "Secrets",
 "Victims",
 "Paranoia",
 "Countdown",
 "Runaway",
 "Folly",
 "Manhunt",
 "Parasites",
 "Pique",
 "Scourge",
 "Season 3",
 "Repression",
 "Wrath",
 "Stolen",
 "Rooftop",
 "Tangled",
 "Redemption",
 "Sacrifice",
 "Inheritance",
 "Care",
 "Ridicule",
 "Monogamy",
 "Protection",
 "Prodigy",
 "Counterfeit",
 "Execution",
 "Popular",
 "Surveillance",
 "Guilt",
 "Justice",
 "Freed",
 "Denial",
 "Competence",
 "Silence",
 "Season 4",
 "Chameleon",
 "Deception",
 "Vulnerable",
 "Lust",
 "Disappearing Acts",
 "Angels",
 "Dolls",
 "Waste",
 "Juvenile",
 "Resilience",
 "Damaged",
 "Risk",
 "Rotten",
 "Mercy",
 "Pandora",
 "Tortured",
 "Privilege",
 "Desperate",
 "Appearances",
 "Dominance",
 "Fallacy",
 "Futility",
 "Grief",
 "Perfect",
 "Soulless",
 "Season 5",
 "Tragedy",
 "Manic",
 "Mother",
 "Loss",
 "Serendipity",
 "Coerced",
 "Choice",
 "Abomination",
 "Control",
 "Shaken",
 "Escape",
 "Brotherhood",
 "Hate",
 "Ritual",
 "Families",
 "Home",
 "Mean",
 "Careless",
 "Sick",
 "Lowdown",
 "Criminal",
 "Painless",
 "Bound",
 "Poison",
 "Head",
 "Season 6",
 "Birthright",
 "Debt",
 "Obscene",
 "Scavenger",
 "Outcry",
 "Conscience",
 "Charisma",
 "Doubt",
 "Weak",
 "Haunted",
 "Contagious",
 "Identity",
 "Quarry",
 "Game",
 "Hooked",
 "Ghost",
 "Rage",
 "Pure",
 "Intoxicated",
 "Night",
 "Blood",
 "Parts",
 "Goliath",
 "Season 7",
 "Demons",
 "Design",
 "911",
 "Ripped",
 "Strain",
 "Raw",
 "Name",
 "Starved",
 "Rockabye",
 "Storm",
 "Alien",
 "Infected",
 "Blast",
 "Manipulated",
 "Gone",
 "Class",
 "Venom",
 "Fault",
 "Fat",
 "Web",
 "Influence",
 "Season 8",
 "Informed",
 "Clock",
 "Recall",
 "Uncle",
 "Confrontation",
 "Infiltrated",
 "Underbelly",
 "Cage",
 "Choreographed",
 "Scheherazade!",
 "Burned",
 "Outsider",
 "Loophole",
 "Dependent",
 "Haystack",
 "Philadelphia",
 "Sin",
 "Responsible",
 "Florida",
 "Annihilated",
 "Pretend",
 "Screwed",
 "Season 9",
 "Alternate",
 "Avatar",
 "Impulsive",
 "Savant",
 "Harm",
 "Svengali",
 "Blinded",
 "Fight",
 "Paternity",
 "Snitch",
 "Streetwise",
 "Signature",
 "Unorthodox",
 "Inconceivable",
 "Undercover",
 "Closet",
 "Authority",
 "Trade",
 "Cold",
 "Season 10",
 "Trials",
 "Confession",
 "Swing",
 "Lunacy",
 "Retro",
 "Babes",
 "Wildlife",
 "Persona",
 "PTSD",
 "Smut",
 "Stranger",
 "Hothouse",
 "Snatched",
 "Transitions",
 "Lead",
 "Ballerina",
 "Hell",
 "Baggage",
 "Selfish",
 "Crush",
 "Liberties",
 "Zebras",
 "Season 11",
 "Unstable",
 "Sugar",
 "Solitary",
 "Hammered",
 "Hardwired",
 "Spooked",
 "Users",
 "Turmoil",
 "Perverted",
 "Anchor",
 "Anchor",
 "Shadow",
 "P.C",
 "Savior",
 "Confidential",
 "Witness",
 "Disabled",
 "Bedtime",
 "Conned",
 "Beef",
 "Torch",
 "Ace", 
 "Wannabe",
 "Shattered",
 "Season 12",
 "Locum",
 "Bullseye",
 "Behave",
 "Merchandise",
 "Wet",
 "Branded",
 "Trophy",
 "Penetration",
 "Gray",
 "Rescue",
 "Pop",
 "Possessed",
 "Mask",
 "Dirty",
 "Flight",
 "Spectacle",
 "Pursuit",
 "Bully",
 "Bombshell",
 "Totem",
 "Reparations",
 "Bang",
 "Delinquent",
 "Smoked",
 "End",
 "",
};
// this is the int array that makes it so slides don't render on top of one another, its also the page number
int[] slideCount = {
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 
};

class Slide {

 Slide() {}

// the function that displays the current slide
 void display(int slidenumber) {

  PFont courier;
  courier = createFont("courierPrime.ttf", 1);
  textFont(courier);
  fill(255);
  noStroke();
  rect(110, 110, 570, 480);
  rect(110, 70, 700, 480);
  fill(0);
  
  textAlign(LEFT);
  textSize(20);
  frameRate(5);
  text(storytext[slidenumber], 110, 130, 570, 380);
  //typewriteText(storytext[slidenumber]);
  //this code creates a new instance of typeface courier, displays the episode text, and paints over the previous slide

  PFont courierB;
  courierB = createFont("Courier Prime Bold.ttf", 1);
  textFont(courierB);
  textSize(40);
  text(eptitle[slidenumber], 110, 70, 570, 380);
 //typewriter(eptitle[slidenumber]);
 }// this code displays the episode title

 void update() {
  color(255);

  textSize(100);
  textAlign(CENTER);
  text(storytext[slidenumber], 110, 110, 570, 280);
 }

// the lower two functions are failed attempts of making a typewriter-esque animation for the text, which I'm having problems implementing but didnt have the heart to delete.

 void typewriter(String text) {
  String msg = "";
  int length = text.length();
  text(msg,  110, 70, 570, 380);
  for (int i = 0; i < length; i++) {

   msg += text.charAt(i);
    print(msg + "  ");
   frameRate(5);
   delay(100);
   text(text.substring(0, i + 1),  110, 70, 570, 380);


  }

 }

 void typewriteText(String text) {
  counter = 0;
  if (counter < text.length())
  text(text.substring(0, counter), 110, 130, 570, 380);
  print(text.substring(0, counter));
  delay(10);
  counter++;


 }
}